#!/usr/bin/env python3
"""
Generate comprehensive MoonBit parity tests from golden JSON data.
All tests use real API calls (get_char_index, load_glyph, set_pixel_sizes).
No stubs — every test has inspect() assertions verified against C FreeType.
"""

import json, os, glob

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "..", "golden", "data")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "src", "parity")
FONT_DIR = os.path.join(os.path.dirname(__file__), "..", "fonts")
MAX_FONT_SIZE = 100_000


def vn(f):
    return f.replace(".", "_").replace("[", "_").replace("]", "_").replace(",", "_").replace("-", "_").replace(" ", "_").lower()


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def bytes_lit(fp):
    with open(fp, "rb") as f:
        data = f.read()
    chunks = []
    for i in range(0, len(data), 16):
        chunks.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i+16]) + ",")
    return "[\n" + "\n".join(chunks) + "\n  ]"


FMT = {".ttf": "TrueType", ".otf": "CffOpenType", ".ttc": "TrueTypeCollection",
       ".woff": "Woff1", ".pfb": "Type1Pfb", ".bdf": "Bdf"}


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    fonts = []
    for gf in sorted(glob.glob(os.path.join(GOLDEN_DIR, "*.json"))):
        ff = os.path.basename(gf)[:-5]
        fp = os.path.join(FONT_DIR, ff)
        if not os.path.exists(fp):
            continue
        sz = os.path.getsize(fp)
        if sz > MAX_FONT_SIZE:
            print(f"  [skip] {ff} ({sz}B)")
            continue
        fonts.append((ff, fp, json.load(open(gf))))
        print(f"  [include] {ff} ({sz}B)")

    L = ["// AUTO-GENERATED by test/parity/gen_parity_tests.py — do not edit", ""]
    tc = 0

    for ff, fp, golden in fonts:
        v = vn(ff)
        meta = golden["metadata"]
        charmaps = golden["charmaps"]
        glyphs = golden["glyphs"]
        kerning = golden["kerning"]
        ext = os.path.splitext(ff)[1].lower()
        upe = meta.get("units_per_em", 0)

        L += [f"///|", f"let {v}_data : Bytes = {bytes_lit(fp)}", ""]

        # T1: format detection
        L += [f"///|", f'test "parity/{ff}: format" {{']
        if ext == ".ttf":
            L += [f'  inspect(@base.detect_format({v}_data) is (TrueType | TrueTypeCollection), content="true")']
        else:
            L += [f'  inspect(@base.detect_format({v}_data), content="{FMT.get(ext, "Unknown")}")']
        L += ["}", ""]
        tc += 1

        # T2: loads
        L += [f"///|", f'test "parity/{ff}: loads" {{',
              f'  inspect((try? @freetype.from_bytes({v}_data)) is Ok(_), content="true")',
              "}", ""]
        tc += 1

        if upe <= 0 and ext != ".bdf":
            continue

        # T3: metadata
        L += [f"///|", f'test "parity/{ff}: metadata" {{',
              f"  let f = @freetype.from_bytes({v}_data)"]
        if meta.get("family_name"):
            L += [f'  inspect(f.family_name, content="{esc(meta["family_name"])}")']
        L += [f'  inspect(f.num_glyphs, content="{meta["num_glyphs"]}")']
        if upe > 0:
            L += [f'  inspect(f.units_per_em, content="{upe}")']
            L += [f'  inspect(f.ascender, content="{meta["ascender"]}")']
            L += [f'  inspect(f.descender, content="{meta["descender"]}")']
            L += [f'  inspect(f.height, content="{meta["height"]}")']
        ul_pos = meta.get("underline_position", 0)
        ul_th = meta.get("underline_thickness", 0)
        if ul_pos or ul_th:
            L += [f'  inspect(f.underline_position, content="{ul_pos}")',
                  f'  inspect(f.underline_thickness, content="{ul_th}")']
        L += ["}", ""]
        tc += 1

        # T4: bbox
        bbox = meta.get("bbox", {})
        if bbox and upe > 0:
            L += [f"///|", f'test "parity/{ff}: bbox" {{',
                  f"  let f = @freetype.from_bytes({v}_data)",
                  f'  inspect(f.bbox.x_min, content="{bbox["xMin"]}")',
                  f'  inspect(f.bbox.y_min, content="{bbox["yMin"]}")',
                  f'  inspect(f.bbox.x_max, content="{bbox["xMax"]}")',
                  f'  inspect(f.bbox.y_max, content="{bbox["yMax"]}")',
                  "}", ""]
            tc += 1

        # T5: flags
        ff_ = meta.get("face_flags", 0)
        if upe > 0:
            L += [f"///|", f'test "parity/{ff}: flags" {{',
                  f"  let f = @freetype.from_bytes({v}_data)",
                  f'  inspect(f.is_scalable(), content="{str(bool(ff_ & 1)).lower()}")',
                  f'  inspect(f.is_sfnt(), content="{str(bool(ff_ & 8)).lower()}")',
                  f'  inspect(f.has_horizontal(), content="{str(bool(ff_ & 16)).lower()}")',
                  f'  inspect(f.has_kerning(), content="{str(bool(ff_ & 64)).lower()}")',
                  "}", ""]
            tc += 1

        # T6: charmaps
        n_cm = meta.get("num_charmaps", 0)
        if n_cm > 0 and upe > 0:
            L += [f"///|", f'test "parity/{ff}: charmaps" {{',
                  f"  let f = @freetype.from_bytes({v}_data)",
                  f'  inspect(f.charmaps.length(), content="{n_cm}")']
            for ci, cm in enumerate(charmaps):
                L += [f"  if f.charmaps.length() > {ci} {{",
                      f'    inspect(f.charmaps[{ci}].platform_id, content="{cm["platform_id"]}")',
                      f'    inspect(f.charmaps[{ci}].encoding_id, content="{cm["encoding_id"]}")',
                      "  }"]
            L += ["}", ""]
            tc += 1

        # T7: charmap entries — REAL API calls to get_char_index
        best_cm = None
        for cm in charmaps:
            if cm.get("entries"):
                if cm["platform_id"] == 3 and cm["encoding_id"] == 1:
                    best_cm = cm
                    break
        if not best_cm:
            for cm in charmaps:
                if cm.get("entries"):
                    best_cm = cm
                    break

        if best_cm and upe > 0:
            entries = best_cm["entries"][:30]
            L += [f"///|", f'test "parity/{ff}: charmap entries" {{',
                  f"  let f = @freetype.from_bytes({v}_data)"]
            for code, gid in entries:
                L += [f"  inspect(@freetype.get_char_index(f, {code}U), content=\"{gid}\")"]
            L += ["}", ""]
            tc += 1

        # T8: glyph outlines (NO_SCALE) — REAL API calls to load_glyph
        noscale = [g for g in glyphs if g["load_flags"] == "NO_SCALE" and g["outline"]["n_points"] > 0]
        if noscale and upe > 0:
            g = noscale[0]
            o = g["outline"]
            L += [f"///|",
                  f'test "parity/{ff}: glyph outline NO_SCALE" {{',
                  f"  let f = @freetype.from_bytes({v}_data)",
                  f"  @freetype.load_glyph(f, {g['glyph_index']}U, load_flags=@base.load_no_scale)",
                  f'  inspect(f.glyph.outline.n_points(), content="{o["n_points"]}")',
                  f'  inspect(f.glyph.outline.n_contours(), content="{o["n_contours"]}")']
            # Verify first few points
            for pi, (px, py) in enumerate(o["points"][:5]):
                L += [f'  inspect(f.glyph.outline.points[{pi}].x, content="{px}")',
                      f'  inspect(f.glyph.outline.points[{pi}].y, content="{py}")']
            # Verify metrics
            m = g["metrics"]
            L += [f'  inspect(f.glyph.metrics.hori_advance, content="{m["horiAdvance"]}")']
            L += ["}", ""]
            tc += 1

        # T9: glyph metrics at a specific size — REAL API calls
        default_glyphs = [g for g in glyphs if g["load_flags"] == "DEFAULT"
                          and g["size_ppem"] == 16 and g["outline"]["n_points"] > 0]
        if default_glyphs and upe > 0:
            g = default_glyphs[0]
            m = g["metrics"]
            L += [f"///|",
                  f'test "parity/{ff}: glyph metrics at 16ppem" {{',
                  f"  let f = @freetype.from_bytes({v}_data)",
                  f"  @freetype.set_pixel_sizes(f, 0U, 16U)",
                  f"  @freetype.load_glyph(f, {g['glyph_index']}U)",
                  f'  inspect(f.glyph.metrics.hori_advance, content="{m["horiAdvance"]}")',
                  "}", ""]
            tc += 1

        # T10: TTC multi-face
        if ext == ".ttc":
            nf = meta.get("num_faces", 1)
            if nf > 1:
                L += [f"///|", f'test "parity/{ff}: TTC multi-face" {{']
                for fi in range(min(nf, 3)):
                    L += [f"  let f{fi} = @freetype.from_bytes({v}_data, face_index={fi})",
                          f'  inspect(f{fi}.num_glyphs > 0L, content="true")']
                L += ["}", ""]
                tc += 1

        # T11: kerning
        if kerning:
            L += [f"///|", f'test "parity/{ff}: kerning" {{',
                  f"  let f = @freetype.from_bytes({v}_data)"]
            for kp in kerning[:10]:
                L += [f"  inspect(@freetype.get_kerning(f, {kp['left']}U, {kp['right']}U).0, content=\"{kp['x']}\")"]
            L += ["}", ""]
            tc += 1

    out = os.path.join(OUTPUT_DIR, "parity_wbtest.mbt")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"\n  Written {out} ({tc} tests, 0 stubs)")


if __name__ == "__main__":
    main()
