#!/usr/bin/env python3
"""
Generate MoonBit parity test source files from golden JSON data.

Reads golden JSON files from test/golden/data/ and generates a single
MoonBit test file in src/parity/ with embedded font bytes and parity checks.

Only processes fonts < 100KB to keep the generated source manageable.

Usage: python3 test/parity/gen_parity_tests.py
"""

import json
import os

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "..", "golden", "data")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "src", "parity")
FONT_DIR = os.path.join(os.path.dirname(__file__), "..", "fonts")
MAX_FONT_SIZE = 100_000  # 100KB limit for embedded fonts


def escape_mbt(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def varname(filename):
    name = filename.replace(".", "_").replace("[", "_").replace("]", "_")
    name = name.replace(",", "_").replace("-", "_").replace(" ", "_")
    return name.lower()


def bytes_literal(filepath):
    with open(filepath, "rb") as f:
        data = f.read()
    chunks = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
        chunks.append(f"    {hex_bytes},")
    return "[\n" + "\n".join(chunks) + "\n  ]"


def format_for_ext(ext):
    return {
        ".ttf": "TrueType",
        ".otf": "CffOpenType",
        ".ttc": "TrueTypeCollection",
        ".woff": "Woff1",
        ".pfb": "Type1Pfb",
        ".bdf": "Bdf",
        ".pcf": "Pcf",
    }.get(ext, "Unknown")


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Collect fonts with golden data, under size limit
    fonts = []
    for golden_file in sorted(os.listdir(GOLDEN_DIR)):
        if not golden_file.endswith(".json"):
            continue
        font_filename = golden_file[:-5]
        font_path = os.path.join(FONT_DIR, font_filename)
        if not os.path.exists(font_path):
            continue
        fsize = os.path.getsize(font_path)
        if fsize > MAX_FONT_SIZE:
            print(f"  [skip] {font_filename} ({fsize} bytes > {MAX_FONT_SIZE})")
            continue
        golden_path = os.path.join(GOLDEN_DIR, golden_file)
        with open(golden_path) as f:
            golden = json.load(f)
        fonts.append((font_filename, font_path, golden))
        print(f"  [include] {font_filename} ({fsize} bytes)")

    if not fonts:
        print("No fonts eligible for parity tests.")
        return

    # Generate a single combined test file (wbtest so it can see package data)
    lines = []
    lines.append("// AUTO-GENERATED by test/parity/gen_parity_tests.py — do not edit")
    lines.append("")

    test_count = 0
    for font_filename, font_path, golden in fonts:
        vn = varname(font_filename)
        meta = golden.get("metadata", {})
        charmaps = golden.get("charmaps", [])
        ext = os.path.splitext(font_filename)[1].lower()
        fmt_name = format_for_ext(ext)

        # Emit data
        lines.append(f"///|")
        lines.append(f"let {vn}_data : Bytes = {bytes_literal(font_path)}")
        lines.append("")

        # Test 1: format detection
        lines.append(f"///|")
        lines.append(f'test "parity/{font_filename}: format detection" {{')
        lines.append(f"  let format = @base.detect_format({vn}_data)")
        if ext == ".ttf":
            lines.append(f'  inspect(format is (TrueType | TrueTypeCollection), content="true")')
        else:
            lines.append(f'  inspect(format, content="{fmt_name}")')
        lines.append("}")
        lines.append("")
        test_count += 1

        # Test 2: loads without error
        lines.append(f"///|")
        lines.append(f'test "parity/{font_filename}: loads without error" {{')
        lines.append(f"  let result = try? @freetype.from_bytes({vn}_data)")
        lines.append(f'  inspect(result.is_ok(), content="true")')
        lines.append("}")
        lines.append("")
        test_count += 1

        upe = meta.get("units_per_em", 0)
        if upe > 0:
            # Test 3: metadata
            lines.append(f"///|")
            lines.append(f'test "parity/{font_filename}: metadata" {{')
            lines.append(f"  let face = @freetype.from_bytes({vn}_data)")
            if meta.get("family_name"):
                lines.append(f'  inspect(face.family_name, content="{escape_mbt(meta["family_name"])}")')
            lines.append(f'  inspect(face.num_glyphs, content="{meta["num_glyphs"]}")')
            lines.append(f'  inspect(face.units_per_em, content="{meta["units_per_em"]}")')
            if meta.get("ascender"):
                lines.append(f'  inspect(face.ascender, content="{meta["ascender"]}")')
            if meta.get("descender"):
                lines.append(f'  inspect(face.descender, content="{meta["descender"]}")')
            if meta.get("height"):
                lines.append(f'  inspect(face.height, content="{meta["height"]}")')
            lines.append("}")
            lines.append("")
            test_count += 1

            # Test 4: bbox
            bbox = meta.get("bbox", {})
            if bbox:
                lines.append(f"///|")
                lines.append(f'test "parity/{font_filename}: bbox" {{')
                lines.append(f"  let face = @freetype.from_bytes({vn}_data)")
                lines.append(f'  inspect(face.bbox.x_min, content="{bbox["xMin"]}")')
                lines.append(f'  inspect(face.bbox.y_min, content="{bbox["yMin"]}")')
                lines.append(f'  inspect(face.bbox.x_max, content="{bbox["xMax"]}")')
                lines.append(f'  inspect(face.bbox.y_max, content="{bbox["yMax"]}")')
                lines.append("}")
                lines.append("")
                test_count += 1

            # Test 5: flags
            face_flags = meta.get("face_flags", 0)
            lines.append(f"///|")
            lines.append(f'test "parity/{font_filename}: flags" {{')
            lines.append(f"  let face = @freetype.from_bytes({vn}_data)")
            if face_flags & 1:
                lines.append(f'  inspect(face.is_scalable(), content="true")')
            else:
                lines.append(f'  inspect(face.is_scalable(), content="false")')
            if face_flags & 8:
                lines.append(f'  inspect(face.is_sfnt(), content="true")')
            if face_flags & 16:
                lines.append(f'  inspect(face.has_horizontal(), content="true")')
            if face_flags & 64:
                lines.append(f'  inspect(face.has_kerning(), content="true")')
            lines.append("}")
            lines.append("")
            test_count += 1

            # Test 6: charmap count
            n_charmaps = meta.get("num_charmaps", 0)
            if n_charmaps > 0:
                lines.append(f"///|")
                lines.append(f'test "parity/{font_filename}: charmaps" {{')
                lines.append(f"  let face = @freetype.from_bytes({vn}_data)")
                lines.append(f'  inspect(face.charmaps.length(), content="{n_charmaps}")')
                lines.append("}")
                lines.append("")
                test_count += 1

            # Test 7: underline
            ul_pos = meta.get("underline_position", 0)
            ul_thick = meta.get("underline_thickness", 0)
            if ul_pos != 0 or ul_thick != 0:
                lines.append(f"///|")
                lines.append(f'test "parity/{font_filename}: underline" {{')
                lines.append(f"  let face = @freetype.from_bytes({vn}_data)")
                lines.append(f'  inspect(face.underline_position, content="{ul_pos}")')
                lines.append(f'  inspect(face.underline_thickness, content="{ul_thick}")')
                lines.append("}")
                lines.append("")
                test_count += 1

        elif ext == ".bdf":
            # BDF-specific: just check it loads and has glyphs
            lines.append(f"///|")
            lines.append(f'test "parity/{font_filename}: metadata" {{')
            lines.append(f"  let face = @freetype.from_bytes({vn}_data)")
            lines.append(f'  inspect(face.num_glyphs, content="{meta["num_glyphs"]}")')
            lines.append("}")
            lines.append("")
            test_count += 1

    # Write output
    test_file = os.path.join(OUTPUT_DIR, "parity_wbtest.mbt")
    with open(test_file, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\n  Written {test_file} ({test_count} tests across {len(fonts)} fonts)")

    # Remove old files if they exist
    for old in ["parity_data.mbt", "parity_test.mbt"]:
        old_path = os.path.join(OUTPUT_DIR, old)
        if os.path.exists(old_path):
            os.remove(old_path)
            print(f"  Removed old {old}")


if __name__ == "__main__":
    main()
