#!/bin/bash
# Download comprehensive test fonts for FreeType MoonBit port parity testing.
# Covers every font format with real-world, production fonts.
# All fonts are freely licensed (Apache 2.0, OFL, or equivalent).
set -euo pipefail

FONT_DIR="$(cd "$(dirname "$0")" && pwd)"

download() {
  local url="$1" dest="$2"
  if [ -f "$dest" ]; then
    echo "  [skip] $(basename "$dest")"
    return 0
  fi
  echo "  [download] $(basename "$dest")"
  curl -fsSL --connect-timeout 15 --retry 2 -o "$dest" "$url" 2>/dev/null || {
    echo "  [FAILED] $(basename "$dest")"
    rm -f "$dest"
    return 1
  }
}

echo "Downloading test fonts to $FONT_DIR..."
echo ""

# ── TrueType (.ttf) ─────────────────────────────────────────────────
echo "=== TrueType ==="
# DejaVu Sans — 6253 glyphs, 158 kerning pairs, complex hinting
download \
  "https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.tar.bz2" \
  "$FONT_DIR/dejavu-fonts.tar.bz2"
if [ ! -f "$FONT_DIR/DejaVuSans.ttf" ] && [ -f "$FONT_DIR/dejavu-fonts.tar.bz2" ]; then
  echo "  [extract] DejaVuSans.ttf"
  tar -xjf "$FONT_DIR/dejavu-fonts.tar.bz2" -C "$FONT_DIR" --strip-components=2 \
    "dejavu-fonts-ttf-2.37/ttf/DejaVuSans.ttf" 2>/dev/null || true
fi

# Roboto variable — multi-axis (wdth+wght) variable TrueType
download \
  "https://github.com/google/fonts/raw/main/ofl/roboto/Roboto%5Bwdth%2Cwght%5D.ttf" \
  "$FONT_DIR/Roboto[wdth,wght].ttf"

echo ""

# ── CFF/OpenType (.otf) ─────────────────────────────────────────────
echo "=== CFF/OpenType ==="
# Source Code Pro — 1568 CFF glyphs, monospaced, production font
download \
  "https://github.com/adobe-fonts/source-code-pro/raw/release/OTF/SourceCodePro-Regular.otf" \
  "$FONT_DIR/SourceCodePro-Regular.otf"

echo ""

# ── TrueType Collection (.ttc) ──────────────────────────────────────
echo "=== TrueType Collection ==="
# Noto Sans CJK — real-world TTC with multiple faces, large CJK charmap
# Using the "Regular" subset TTC (smaller than full)
# Real TTC fonts are very large (Noto Sans CJK is ~16MB).
# We use minimal.ttc for format testing since TTC is just a collection
# header over regular SFNT data — TTF/CFF testing covers the core.
echo "  [note] Using synthetic minimal.ttc (real TTC fonts are 16MB+)"
echo "  [note] To test with real TTC, manually download NotoSansCJK-Regular.ttc:"
echo "         https://github.com/notofonts/noto-cjk/releases (look for OTC/TTC files)"

echo ""

# ── WOFF (.woff) ─────────────────────────────────────────────────────
echo "=== WOFF ==="
# WOFF1 is a legacy format (zlib-compressed SFNT wrapper).
# Modern servers serve WOFF2 (Brotli), so real WOFF1 files are hard to find.
# We use minimal.woff generated by generate_test_fonts.py — it's a valid
# WOFF1 wrapping of minimal.ttf with real zlib compression.
echo "  [note] Using synthetic minimal.woff (WOFF1 is legacy; servers serve WOFF2 now)"

echo ""

# ── Type 1 PFB (.pfb) ───────────────────────────────────────────────
echo "=== Type 1 PFB ==="
# Nimbus Sans — URW clone of Helvetica, 855 glyphs, real Type 1
download \
  "https://github.com/ArtifexSoftware/urw-base35-fonts/raw/master/fonts/NimbusSans-Regular.t1" \
  "$FONT_DIR/NimbusSans-Regular.pfb" || true

echo ""

# ── BDF Bitmap (.bdf) ───────────────────────────────────────────────
echo "=== BDF Bitmap ==="
# GNU Unifont — 57087 glyphs covering most of Unicode, real BDF
download \
  "https://unifoundry.com/pub/unifont/unifont-16.0.02/font-builds/unifont-16.0.02.bdf.gz" \
  "$FONT_DIR/unifont.bdf.gz"
if [ ! -f "$FONT_DIR/unifont.bdf" ] && [ -f "$FONT_DIR/unifont.bdf.gz" ]; then
  echo "  [extract] unifont.bdf"
  gunzip -k "$FONT_DIR/unifont.bdf.gz" 2>/dev/null || true
fi

echo ""

# ── Summary ──────────────────────────────────────────────────────────
echo "=== Available fonts ==="
for f in "$FONT_DIR"/*.ttf "$FONT_DIR"/*.otf "$FONT_DIR"/*.ttc "$FONT_DIR"/*.bdf "$FONT_DIR"/*.pfb "$FONT_DIR"/*.woff; do
  [ -f "$f" ] && printf "  %-45s %s\n" "$(basename "$f")" "$(du -h "$f" | cut -f1)"
done
echo ""
echo "Formats covered: TTF, OTF/CFF, TTC (if available), PFB, BDF"
echo "WOFF: generated from TTF by test/fonts/generate_test_fonts.py"
echo "See LICENSES.md for license details."
